JUCE Designer: BigTree Class Reference
BigTree Class Reference
This class holds all object hierarchy and property modification.
Public Member Functions
BigTree ()
Creates an invalid BigTree.
BigTree (const ValueTree &other)
Creates a reference to another BigTree.
BigTree (DynamicObject *object, var _type)
Creates a named type BigTree that holds a DynamicObject.
BigTree (DynamicObject *object)
Creates an unnamed BigTree that holds a DynamicObject.
void setDynamicObject (DynamicObject *object)
void valueTreePropertyChanged (ValueTree &treeWhosePropertyHasChanged, const Identifier &property)
Deals with property changes on a determinated object.
void valueTreeChildAdded (ValueTree &parentTree, ValueTree &childWhichHasBeenAdded)
void valueTreeChildRemoved (ValueTree &parentTree, ValueTree &childWhichHasBeenRemoved)
void valueTreeChildOrderChanged (ValueTree &parentTreeWhoseChildrenHaveMoved)
void valueTreeParentChanged (ValueTree &treeWhoseParentHasChanged)
void valueTreeRedirected (ValueTree &treeWhichHasBeenChanged)
BigTree & getChildWithProperty (const Identifier &propertyName, const var &propertyValue, bool recursive)
Looks for any BigTree within it's childs, recursive or not, that has the named property with specified value.
BigTree getChild (int index) const
Returns a BigTree that references a child BigTree on the given index.
void recursive_removeProperty (Identifier name, UndoManager *undoManager)
Recursive function to remove a named property from this BigTree and all it's children.
XmlElement * createXml ()
Returns an XmlElement containing the representation of the current BigTree and all it's children.
Detailed Description
This class holds all object hierarchy and property modification.
Definition at line 24 of file BigTree.h.
Constructor & Destructor Documentation
BigTree::BigTree ()
Creates an invalid BigTree.
See Also
ValueTree
Definition at line 15 of file BigTree.cpp.
Referenced by createXml(), getChild(), and getChildWithProperty().
BigTree::BigTree (const ValueTree & other)
Creates a reference to another BigTree.
Definition at line 20 of file BigTree.cpp.
BigTree::BigTree (DynamicObject * object, var _type)
Creates a named type BigTree that holds a DynamicObject.
Definition at line 25 of file BigTree.cpp.
BigTree::BigTree (DynamicObject * object)
Creates an unnamed BigTree that holds a DynamicObject.
Definition at line 30 of file BigTree.cpp.
Member Function Documentation
XmlElement * BigTree::createXml ()
Returns an XmlElement containing the representation of the current BigTree and all it's children.
Definition at line 199 of file BigTree.cpp.
References BigTree(), createXml(), and recursive_removeProperty().
Referenced by createXml().
BigTree BigTree::getChild (int index) const
Returns a BigTree that references a child BigTree on the given index.
Definition at line 186 of file BigTree.cpp.
References BigTree().
Referenced by getChildWithProperty(), and recursive_removeProperty().
BigTree & BigTree::getChildWithProperty (const Identifier & propertyName, const var & propertyValue, bool recursive)
Looks for any BigTree within it's childs, recursive or not, that has the named property with specified value.
It will look in this tree first for the given property, then, it's children and if recursive is set, children's children and so on.
See Also
Attributes
Constructor::getAttributeOf
Attribute
Parameters
propertyName Identifier matching a property name.
propertyValue var containing the value to look for.
recursive bool set to look into children's children and so on.
Definition at line 150 of file BigTree.cpp.
References BigTree(), and getChild().
Referenced by PlaceableComponent::perform(), and PlaceableComponent::undo().
void BigTree::recursive_removeProperty (Identifier name, UndoManager * undoManager)
Recursive function to remove a named property from this BigTree and all it's children.
Definition at line 191 of file BigTree.cpp.
References getChild(), and recursive_removeProperty().
Referenced by createXml(), and recursive_removeProperty().
void BigTree::valueTreePropertyChanged (ValueTree & treeWhosePropertyHasChanged, const Identifier & property)
Deals with property changes on a determinated object.
Definition at line 36 of file BigTree.cpp.
References Constructor::getAttributeOf(), Constructor::getInstance(), and Constructor::getUndoManager().
The documentation for this class was generated from the following files:
C:/Users/admin/juced/Source/Designer/BigTree.h
C:/Users/admin/juced/Source/Designer/BigTree.cpp