JUCE Designer: Constructor Class Reference
Constructor Class Reference
Object required to build components and show its properties.
Public Member Functions
~Constructor ()
Destructor.
void loadAttributesFromXmlFile (const File &xmlFile)
Function called within JUCE_Designer constructor.
void loadEnumerationsFromXmlFile (const File &xmlFile)
Function called within JUCE_Designer constructor.
Attribute * getAttributeOf (Identifier _name)
Returns a struct pointer of attribute parameters given it's Identifier.
Array< Enumeration * > * getEnumerationsOf (Identifier _name)
Returns a pointer to an array of Enumeration pointers given it's Identifier.
UndoManager * getUndoManager ()
Returns a pointer to an UndoManager.
SelectionArea * getSelectionBox ()
Returns a pointer to the selection box that envolves the selected component.
void setDrawBoundsMod (int x, int y, int width, int height)
Method related to the selection box (SelectionArea).
int getDrawBoundsModX ()
Method related to the selection box (SelectionArea).
int getDrawBoundsModY ()
Method related to the selection box (SelectionArea).
int getDrawBoundsModWidth ()
Method related to the selection box (SelectionArea).
int getDrawBoundsModHeight ()
Method related to the selection box (SelectionArea).
void setGridSize (int newGridSize)
Sets the size in pixels between the grid lines.
int getGridSize ()
Returns the size in pixels between the grid lines.
Component * getSelectedComponent ()
void setSelectedComponent (Component *selectedComponent)
Sets the current selected component.
void setDesigner (Component *juce_designer)
Sets a pointer to an instance of JUCE_Designer.
Component * getDesigner ()
Gets a Component pointer to an instance of JUCE_Designer.
void setBigTreeRoot (const BigTree &bigTreeRoot)
Sets the root of BigTree's to the value passed by reference.
BigTree getBigTreeRoot ()
Returns a reference to the BigTree root.
Component * createComponent (String selectedToolName, String parentComponentID, Rectangle< int > bounds)
Create and add a component to the editor.
Static Public Member Functions
static Constructor * getInstance ()
This function is called to create an instance of the class.
static void destroy ()
This function is called statically to destroy the instance of this class.
static void log (String msg)
Static method to write a line to designer.log file.
Public Attributes
BigTree _bigTreeRoot
Friends
class SelectionArea
class JUCE_Designer
class PlaceableComponent
Detailed Description
Object required to build components and show its properties.
Only one instance of this object is allowed.
To use, simply get an instance of this class using the getInstance() static method. Example: Constructor *constructor = Constructor::getInstance();
Definition at line 36 of file Constructor.h.
Constructor & Destructor Documentation
Constructor::~Constructor ()
Destructor.
Definition at line 34 of file Constructor.cpp.
References getBigTreeRoot(), log(), and BigTree::recursive_removeProperty().
Member Function Documentation
Component * Constructor::createComponent (String selectedToolName, String parentComponentID, Rectangle< int > bounds)
Create and add a component to the editor.
Parameters
selectedToolName String containing the name of a tool set in PlaceableComponent::createObjectFromToolName
parentComponentID String containing the ID of the parent component
bounds Rectangle<int> of the space that will occupy in the parent component
Definition at line 263 of file Constructor.cpp.
References PlaceableComponent::getComponent(), and getUndoManager().
void Constructor::destroy () static
This function is called statically to destroy the instance of this class.
Definition at line 28 of file Constructor.cpp.
References log().
Attribute * Constructor::getAttributeOf (Identifier _name)
Returns a struct pointer of attribute parameters given it's Identifier.
Parameters
_name Attribute identifier.
See Also
Attribute
Attributes
Definition at line 119 of file Constructor.cpp.
Referenced by BigTree::valueTreePropertyChanged().
BigTree Constructor::getBigTreeRoot ()
Returns a reference to the BigTree root.
Definition at line 255 of file Constructor.cpp.
Referenced by PlaceableComponent::perform(), and ~Constructor().
Component * Constructor::getDesigner ()
Gets a Component pointer to an instance of JUCE_Designer.
Definition at line 236 of file Constructor.cpp.
Referenced by PlaceableComponent::perform(), and PlaceableComponent::undo().
int Constructor::getDrawBoundsModHeight ()
Method related to the selection box (SelectionArea).
Definition at line 167 of file Constructor.cpp.
int Constructor::getDrawBoundsModWidth ()
Method related to the selection box (SelectionArea).
Definition at line 162 of file Constructor.cpp.
int Constructor::getDrawBoundsModX ()
Method related to the selection box (SelectionArea).
Definition at line 152 of file Constructor.cpp.
int Constructor::getDrawBoundsModY ()
Method related to the selection box (SelectionArea).
Definition at line 157 of file Constructor.cpp.
Array< Enumeration * > * Constructor::getEnumerationsOf (Identifier _name)
Returns a pointer to an array of Enumeration pointers given it's Identifier.
Parameters
_name Attribute identifier.
See Also
Enumeration
Definition at line 128 of file Constructor.cpp.
int Constructor::getGridSize ()
Returns the size in pixels between the grid lines.
Definition at line 177 of file Constructor.cpp.
Constructor * Constructor::getInstance () static
This function is called to create an instance of the class.
Calling the constructor publicly is not allowed. The constructor is private and is only called by this Instance function.
Definition at line 16 of file Constructor.cpp.
Referenced by PlaceableComponent::perform(), PlaceableComponent::undo(), and BigTree::valueTreePropertyChanged().
SelectionArea * Constructor::getSelectionBox ()
Returns a pointer to the selection box that envolves the selected component.
See Also
SelectionArea, getSelectedComponent
Definition at line 192 of file Constructor.cpp.
UndoManager * Constructor::getUndoManager ()
Returns a pointer to an UndoManager.
See Also
UndoManager, BigTree, ValueTree
Definition at line 137 of file Constructor.cpp.
Referenced by createComponent(), and BigTree::valueTreePropertyChanged().
void Constructor::loadAttributesFromXmlFile (const File & xmlFile)
Function called within JUCE_Designer constructor.
Loads all parameters from a list of attribute types in a XML file.
Parameters
xmlFile File object that points to XML file in disc.
See Also
getAttributeOf
Definition at line 64 of file Constructor.cpp.
References log().
void Constructor::loadEnumerationsFromXmlFile (const File & xmlFile)
Function called within JUCE_Designer constructor.
Loads all parameters from a list of enumerations in a XML file.
Parameters
xmlFile File object that points to XML file in disc.
See Also
getEnumerationsOf
Definition at line 87 of file Constructor.cpp.
References log().
void Constructor::log (String msg) static
Static method to write a line to designer.log file.
Definition at line 203 of file Constructor.cpp.
Referenced by BigTree::BigTree(), destroy(), BigTree::getChildWithProperty(), loadAttributesFromXmlFile(), loadEnumerationsFromXmlFile(), PlaceableComponent::perform(), PlaceableComponent::undo(), BigTree::valueTreePropertyChanged(), and ~Constructor().
void Constructor::setBigTreeRoot (const BigTree & bigTreeRoot)
Sets the root of BigTree's to the value passed by reference.
Definition at line 242 of file Constructor.cpp.
Referenced by PlaceableComponent::perform(), and PlaceableComponent::undo().
void Constructor::setDesigner (Component * juce_designer)
Sets a pointer to an instance of JUCE_Designer.
Definition at line 231 of file Constructor.cpp.
void Constructor::setDrawBoundsMod (int x, int y, int width, int height)
Method related to the selection box (SelectionArea).
Definition at line 144 of file Constructor.cpp.
void Constructor::setGridSize (int newGridSize)
Sets the size in pixels between the grid lines.
See Also
getGridSize, JUCE_Designer::Grid
Definition at line 172 of file Constructor.cpp.
void Constructor::setSelectedComponent (Component * selectedComponent)
Sets the current selected component.
Definition at line 187 of file Constructor.cpp.
The documentation for this class was generated from the following files:
C:/Users/admin/juced/Source/Designer/Constructor.h
C:/Users/admin/juced/Source/Designer/Constructor.cpp