JUCE Designer: PlaceableComponent Class Reference
PlaceableComponent Class Reference
This class represents the actions for create, undo and redo of components creation.
Public Member Functions
PlaceableComponent (String selectedToolName, String parentComponentID, Rectangle< int > bounds, String componentID=String::empty)
Creates a PlaceableComponent object.
bool perform ()
Method called by the UndoManager to create the specified component (redo also).
bool undo ()
Method called by the UndoManager to undo the creation of the represented component.
Component * getComponent ()
Returns a pointer to the component being represented by this object.
Friends
class BigTree
Detailed Description
This class represents the actions for create, undo and redo of components creation.
See Also
Constructor::createComponent
Definition at line 38 of file PlaceableComponent.h.
Constructor & Destructor Documentation
PlaceableComponent::PlaceableComponent (String selectedToolName, String parentComponentID, Rectangle< int > bounds, String componentID = String::empty)
Creates a PlaceableComponent object.
Parameters
selectedToolName String containing the name of the component class to represent.
parentComponentID parent's component ID
bounds Rectangle<int> containing the bounds that will occupy the new component.
componentID Optional String that will set component's ID to this value when creating it.
Definition at line 13 of file PlaceableComponent.cpp.
Member Function Documentation
Component * PlaceableComponent::getComponent ()
Returns a pointer to the component being represented by this object.
Definition at line 259 of file PlaceableComponent.cpp.
bool PlaceableComponent::perform ()
Method called by the UndoManager to create the specified component (redo also).
Definition at line 50 of file PlaceableComponent.cpp.
References BigTree::getChildWithProperty(), and Constructor::getInstance().
bool PlaceableComponent::undo ()
Method called by the UndoManager to undo the creation of the represented component.
Definition at line 171 of file PlaceableComponent.cpp.
References BigTree::getChildWithProperty(), and Constructor::getInstance().
The documentation for this class was generated from the following files:
C:/Users/admin/juced/Source/Designer/PlaceableComponent.h
C:/Users/admin/juced/Source/Designer/PlaceableComponent.cpp