/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"


//==============================================================================
class jucedApplication  : public JUCEApplication
{
public:
    //==============================================================================
    jucedApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // This method is where you should put your application's initialisation code..
		if (commandLine.isNotEmpty()) {}	//TODO: remove
        mainWindow = new MainWindow();
		//mainWindow->setFullScreen(true);
    }

    void shutdown()
    {
        // Add your application's shutdown code here..

        mainWindow = nullptr; // (deletes our window)
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
		if (commandLine.isNotEmpty()) {}	//TODO: remove
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    //==============================================================================
    /*
        This class implements the desktop window that contains an instance of
        our MainContentComponent class.
    */
    class MainWindow    : public DocumentWindow
    {
    public:
        MainWindow()  : DocumentWindow ("JUCE Interface Designer",
                                        //Colour((uint8) 27, (uint8) 80, (uint8) 139),	//Colours::hotpink,
										Colour((uint8) 49, (uint8) 124, (uint8) 205),
                                        DocumentWindow::allButtons)
        {
			MainContentComponent* contentComp = new MainContentComponent();
            setContentOwned (contentComp, true);
			setResizable(true, true);
            centreWithSize (getWidth(), getHeight());
            setVisible (true);
			contentComp->setVisible(true);

			//Image LogoImage;
			//LogoImage = ImageFileFormat::loadFrom (BinaryData::juced_png, BinaryData::juced_pngSize);
			

			ApplicationCommandManager* commandManager = Constructor::getInstance()->getCommandManager();
			commandManager->registerAllCommandsForTarget (contentComp);
			commandManager->registerAllCommandsForTarget (JUCEApplication::getInstance());

			// this lets the command manager use keypresses that arrive in our window to send
			// out commands
			addKeyListener (commandManager->getKeyMappings());

			// this tells the DocumentWindow to automatically create and manage a MenuBarComponent
			// which uses our contentComp as its MenuBarModel
			setMenuBar (contentComp);

			// tells our menu bar model that it should watch this command manager for
			// changes, and send change messages accordingly.
			contentComp->setApplicationCommandManagerToWatch (commandManager);
			setUsingNativeTitleBar(true);

        }

        void closeButtonPressed()
        {
            // This is called when the user tries to close this window. Here, we'll just
            // ask the app to quit when this happens, but you can change this to do
            // whatever you need.
            JUCEApplication::getInstance()->systemRequestedQuit();
            
        }


		
		    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainWindow)
    };

private:
    ScopedPointer<MainWindow> mainWindow;

   
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (jucedApplication)
